name: flutter_login
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc:
  equatable: ^1.0.0
  shared_preferences: ^0.5.7
  get: ^1.17.3
  rxdart: ^0.23.1
  json_serializable: ^3.3.0
  build_runner: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test:
  mockito: ^4.0.0

flutter:
  uses-material-design: true
